apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  labels:
       app: productservice
  name: commerce-webservices
spec:
  serviceClassExternalName: cc-occ-commerce-webservices-v2-3258b
  servicePlanExternalName: default
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  labels:
    app: productservice
  name: commercewebservices-binding
spec:
  instanceRef:
    name: commerce-webservices
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: commercewebservices-instance-binding-usage
  labels:
    app: productservice
spec:
 serviceBindingRef:
   name: commercewebservices-binding
 usedBy:
   kind: deployment
   name: productservice-v1