apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: redis-binding
spec:
  instanceRef:
    name: redis
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: redis-instance-binding-usage
  labels:
    app: productservice
spec:
 serviceBindingRef:
   name: redis-binding
 usedBy:
   kind: deployment
   name: productservice-v1
